language: julia
env:
   - CONDA_JL_HOME=$HOME/miniconda/envs/conda_jl PYTHON=$HOME/miniconda/envs/conda_jl/bin/python
os:
  - linux
julia:
  - 1.3
before_install:
  - cd ..
  # Install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.anaconda.com/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  #create julia conda enviornment
  - conda create -n conda_jl --yes python=3.7 conda
  - source activate conda_jl
  - conda install -c rmg --yes rmg
  - conda update --yes conda
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - travis_wait julia -e 'using Pkg; Pkg.add(PackageSpec(path="ReactionMechanismSimulator.jl"));'
  - travis_wait julia -e 'using Pkg; Pkg.build("ReactionMechanismSimulator"); Pkg.test("ReactionMechanismSimulator"; coverage=true);'
after_success: 
  - julia -e 'cd(Pkg.dir("ReactionMechanismSimulator")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
branches:
  only:
    - master
