module ReactionMechanismSimulator
import Logging
Logging.disable_logging(Logging.Warn)
using PythonCall
pyimport("sys").path.append("")
const Chem = Ref{Py}()
const Desc = Ref{Py}()
const molecule = Ref{Py}()
const chemkin = Ref{Py}()
const species = Ref{Py}()
const reaction = Ref{Py}()
const nasa = Ref{Py}()
const wilhoit = Ref{Py}()
const arrhenius = Ref{Py}()
const falloff = Ref{Py}()
const chebyshev = Ref{Py}()
const solvation = Ref{Py}()
const fragment = Ref{Py}()
const pydot = Ref{Py}()
const os = Ref{Py}()
function __init__()
    Chem[] = pyimport("rdkit.Chem")
    Desc[] = pyimport("rdkit.Chem.Descriptors")
    try
        molecule[] = pyimport("rmgpy.molecule")
        chemkin[] = pyimport("rmgpy.chemkin")
        species[] = pyimport("rmgpy.species")
        reaction[] = pyimport("rmgpy.reaction")
        nasa[] = pyimport("rmgpy.thermo.nasa")
        wilhoit[] = pyimport("rmgpy.thermo.wilhoit")
        arrhenius[] = pyimport("rmgpy.kinetics.arrhenius")
        falloff[] = pyimport("rmgpy.kinetics.falloff")
        chebyshev[] = pyimport("rmgpy.kinetics.chebyshev")
        solvation[] = pyimport("rmgpy.data.solvation")
        fragment[] = pyimport("rmgpy.molecule.fragment")
    catch e
        molecule[] = pyimport("molecule.molecule")
        chemkin[] = pyimport("molecule.chemkin")
        species[] = pyimport("molecule.species")
        reaction[] = pyimport("molecule.reaction")
        nasa[] = pyimport("molecule.thermo.nasa")
        wilhoit[] = pyimport("molecule.thermo.wilhoit")
        arrhenius[] = pyimport("molecule.kinetics.arrhenius")
        falloff[] = pyimport("molecule.kinetics.falloff")
        chebyshev[] = pyimport("molecule.kinetics.chebyshev")
        solvation[] = pyimport("molecule.data.solvation")
        fragment[] = pyimport("molecule.molecule.fragment")
    end
    pydot[] = pyimport("pydot")
    os[] = pyimport("os")
end
include("Constants.jl")
include("Tools.jl")
include("Calculators/RateUncertainty.jl")
include("Calculators/ThermoUncertainty.jl")
include("Calculators/Thermo.jl")
include("Calculators/Diffusion.jl")
include("Calculators/Rate.jl")
include("Calculators/Viscosity.jl")
include("Calculators/Thermovec.jl")
include("Calculators/Ratevec.jl")
include("Calculators/kLAkH.jl")
include("Species.jl")
include("Solvent.jl")
include("Reaction.jl")
include("Phase.jl")
include("PhaseState.jl")
include("Interface.jl")
include("Domain.jl")
include("yml.jl")
include("Parse.jl")
include("ModelReduction.jl")
include("Reactor.jl")
include("ThreadedSensitivities.jl")
include("Simulation.jl")
include("TransitorySensitivities.jl")
include("AutomaticMechanismAnalysis.jl")
include("EdgeAnalysis.jl")
include("Debugging.jl")
include("Plotting.jl")
include("fluxdiagrams.jl")
end
