module ReactionMechanismSimulator
    using PyCall
    push!(PyVector(pyimport("sys")["path"]), "")
    const Chem = PyNULL()
    const Desc = PyNULL()
    const molecule = PyNULL()
    const pydot = PyNULL()
    const chemkin =PyNULL()
    const species = PyNULL()
    const reaction = PyNULL()
    const nasa = PyNULL()
    const wilhoit = PyNULL()
    const arrhenius = PyNULL()
    const falloff = PyNULL()
    const chebyshev = PyNULL()
    const solvation = PyNULL()
    const yaml = PyNULL()
    const os = PyNULL()
    function __init__()
        copy!(Chem,pyimport_conda("rdkit.Chem","rdkit","rmg"))
        copy!(Desc,pyimport_conda("rdkit.Chem.Descriptors","rdkit","rmg"))
        copy!(molecule,pyimport_conda("molecule.molecule","rmgmolecule","hwpang"))
        copy!(pydot,pyimport_conda("pydot","pydot"))
        copy!(chemkin,pyimport_conda("molecule.chemkin","rmgmolecule","hwpang"))
        copy!(species,pyimport_conda("molecule.species","rmgmolecule","hwpang"))
        copy!(reaction,pyimport_conda("molecule.reaction","rmgmolecule","hwpang"))
        copy!(nasa,pyimport_conda("molecule.thermo.nasa","rmgmolecule","hwpang"))
        copy!(wilhoit,pyimport_conda("molecule.thermo.wilhoit","rmgmolecule","hwpang"))
        copy!(arrhenius,pyimport_conda("molecule.kinetics.arrhenius","rmgmolecule","hwpang"))
        copy!(falloff,pyimport_conda("molecule.kinetics.falloff","rmgmolecule","hwpang"))
        copy!(chebyshev,pyimport_conda("molecule.kinetics.chebyshev","rmgmolecule","hwpang"))
        copy!(solvation,pyimport_conda("molecule.data.solvation","rmgmolecule","hwpang"))
        copy!(os,pyimport_conda("os","os"))
    end
    include("Constants.jl")
    include("Tools.jl")
    include("Calculators/RateUncertainty.jl")
    include("Calculators/ThermoUncertainty.jl")
    include("Calculators/Thermo.jl")
    include("Calculators/Diffusion.jl")
    include("Calculators/Rate.jl")
    include("Calculators/Viscosity.jl")
    include("Calculators/Thermovec.jl")
    include("Calculators/Ratevec.jl")
    include("Calculators/kLAkH.jl")
    include("Species.jl")
    include("Solvent.jl")
    include("Reaction.jl")
    include("Phase.jl")
    include("PhaseState.jl")
    include("Interface.jl")
    include("Domain.jl")
    include("yml.jl")
    include("Parse.jl")
    include("ModelReduction.jl")
    include("Reactor.jl")
    include("ThreadedSensitivities.jl")
    include("Simulation.jl")
    include("TransitorySensitivities.jl")
    include("AutomaticMechanismAnalysis.jl")
    include("EdgeAnalysis.jl")
    include("Debugging.jl")
    include("Plotting.jl")
    include("fluxdiagrams.jl")
end
