import Logging
Logging.disable_logging(Logging.Warn)

using PythonCall
const Chem = PythonCall.pynew()
const molecule = PythonCall.pynew()
const fragment = PythonCall.pynew()
const pydot = PythonCall.pynew()
PythonCall.pycopy!(Chem, pyimport("rdkit.Chem"))
try
    PythonCall.pycopy!(molecule, pyimport("rmgpy.molecule"))
    PythonCall.pycopy!(fragment, pyimport("rmgpy.molecule.fragment"))
catch e
    PythonCall.pycopy!(molecule, pyimport("molecule.molecule"))
    PythonCall.pycopy!(fragment, pyimport("molecule.molecule.fragment"))
end
PythonCall.pycopy!(pydot, pyimport("pydot"))

include("Constants.jl")
include("Tools.jl")
include("Calculators/RateUncertainty.jl")
include("Calculators/ThermoUncertainty.jl")
include("Calculators/Thermo.jl")
include("Calculators/Diffusion.jl")
include("Calculators/Rate.jl")
include("Calculators/Viscosity.jl")
include("Calculators/kLAkH.jl")
include("Species.jl")
include("Solvent.jl")
include("Reaction.jl")
include("Phase.jl")
include("PhaseState.jl")
include("Interface.jl")
include("Domain.jl")
include("Parse.jl")
include("ModelReduction.jl")
include("Reactor.jl")
include("ThreadedSensitivities.jl")
include("Simulation.jl")
include("TransitorySensitivities.jl")
include("AutomaticMechanismAnalysis.jl")
include("Debugging.jl")
include("EdgeAnalysis.jl")
include("Plotting.jl")
include("fluxdiagrams.jl")
