name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - marcus_development
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Juliaup
        uses: julia-actions/install-juliaup@v2
        with:
          channel: '1.10'

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@v1

      - name: Build
        run: |
            julia -e 'using Pkg; Pkg.develop(Pkg.PackageSpec(path="../ReactionMechanismSimulator.jl/")); Pkg.build("ReactionMechanismSimulator");'

      - name: Run tests
        run: |
            julia -e 'using Pkg; Pkg.test("ReactionMechanismSimulator"; coverage=true)'

      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
