name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - marcus_development
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: 3.7
          activate-environment: rms_env
      - name: Fix PyCall linking
        run: |
            julia -e 'ENV["PYTHON"]=ENV["CONDA"] * "/envs/rms_env/bin/python"; using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall")'
      - uses: julia-actions/julia-buildpkg@v1
      - name: Build
        run: |
            julia -e 'using Pkg; Pkg.develop(PackageSpec(path="../ReactionMechanismSimulator.jl")); Pkg.build("ReactionMechanismSimulator");'
      - name: Run tests
        run: |
            julia -e 'using Pkg; Pkg.test("ReactionMechanismSimulator";coverage=true)'
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
